export const projectCardContent = {
	heart: {
		id: 'heart',
		title: 'Hearts Connected',
		img: ['img/hearts/hearts-home.jpg', ''],
		alt: ['Hearts Connected Homescreen', 'Hearts GIF'],
		tech: ['javascript', 'html', 'typescript', 'react'],
	},
	cv: {
		id: 'cv',
		title: 'Clearviction',
		img: ['img/clearviction/cvhome.jpg', 'img/clearviction/cv-demo.gif'],
		alt: ['Clearviction Homescreen', 'Clearviction Demo GIF'],
		tech: ['javascript', 'html', 'typescript', 'react', 'nextjs'],
	},
	meet: {
		id: 'meet',
		title: 'Meet App',
		img: ['img/meet/meetApp.jpg', 'img/meet/meetDemo.gif'],
		alt: ['Meet Homescreen', 'Meet GIF'],
		tech: ['javascript', 'html', 'typescript', 'react'],
	},
	angular: {
		id: 'angular',
		title: 'MyFlix Angular',
		img: ['img/angular/angular.jpg', 'img/angular/angularDemoCrop.gif'],
		alt: ['Angular myFlix', 'Angular myFlix GIF'],
		tech: ['angular', 'node'],
	},
	myflix: {
		id: 'myflix',
		title: 'MyFlix',
		img: ['./img/myFlix/myFlix.jpg', './img/myFlix/myflixDemo.gif'],
		alt: ['MyFLix Home page', 'myFlix GIF'],
		tech: ['redux', 'bootstrap', 'node', 'react', 'parcel'],
	},
	budget: {
		id: 'budget',
		title: 'Budget Planning Feature',
		img: ['./img/budget/screenshotTop.jpg', './img/budget/demo.gif'],
		alt: ['Budget Planner Home page', 'Budget Planner GIF'],
		tech: ['javascript', 'html', 'typescript', 'react'],
	},
	movie: {
		id: 'movie',
		title: 'Movie API',
		img: ['img/movie/movieAPi.jpg', ''],
		alt: ['movie Api', ''],
		tech: ['node', 'express', 'nosql', 'mongodb', 'mongoose', 'http', 'jwt'],
	},
	ccl: {
		id: 'ccl',
		title: 'CCL Website',
		img: ['img/ccl/homepage.jpg', 'img/ccl/ccl-demo.gif'],
		alt: ['CCL Home Page', 'CCL GIF'],
		tech: ['javascript', 'html', 'squarespace', 'css'],
	},
	chat: {
		id: 'chat',
		title: 'Chat App',
		img: ['img/chat/HomeScreen.jpg', 'img/chat/chatApp.gif'],
		alt: ['chat', 'Chat App Gif'],
		tech: ['native', 'expo', 'firestore', 'firebase'],
	},
	poke: {
		id: 'poke',
		title: 'Pokedex',
		img: ['img/pokedex/pokedex.png', 'img/pokedex/pokedexDemo.gif'],
		alt: ['pokedex', 'Pokedex GIF'],
		tech: ['javascript', 'html', 'api'],
	},
	forkfull: {
		id: 'fork',
		title: 'Changed by the Forkfull',
		img: ['img/changed/changed.jpg', 'img/changed/changedDemo.gif'],
		alt: ['Changed by the Forkfull', 'Changed GIF'],
		tech: ['javascript', 'html'],
	},
};
